### ISSUE TITLE
Uploading on Linux Fails

### ISSUE THREAD

**Issue by mhmayyan** [mcci-catena/Arduino_Core_STM32#180] opened 2021-10-15 18:41 UTC
Hi,

Every time I upload on Linux I get the following:-

```
Program file:   /tmp/arduino_build_120438/CatenaSketch.ino.dfu
Board VID:PID:  0x040E:0x0091
Base address:   0x08005000
Bootloader:     /home/user/.arduino15/packages/mcci/hardware/stm32/3.0.3/bootloaders/McciBootloader_46xx.bin
dfu-util 0.9

Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2016 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to http://sourceforge.net/p/dfu-util/tickets/

Deducing device DFU version from functional descriptor length
Opening DFU capable USB device...
ID 0483:df11
Run-time device DFU version 011a
Claiming USB DFU Interface...
Setting Alternate Setting #0 ...
dfu-util: Invalid DFU suffix signature
dfu-util: A valid DFU suffix will be required in a future dfu-util release!!!
dfu-util: Non-valid multiplier 'g', interpreted as type identifier instead
Determining device status: state = dfuERROR, status = 10
dfuERROR, clearing status
Determining device status: state = dfuIDLE, status = 0
dfuIDLE, continuing
DFU mode device DFU version 011a
Device returned transfer size 2048
DfuSe interface name: "Internal Flash  "
Downloading to address = 0x08000000, size = 10768
Download	[=========================] 100%        10768 bytes
Download done.
File downloaded successfully
dfu-util 0.9

Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2016 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to http://sourceforge.net/p/dfu-util/tickets/

Match vendor ID from file: 040e
Deducing device DFU version from functional descriptor length
Opening DFU capable USB device...
ID 0483:df11
Run-time device DFU version 011a
Claiming USB DFU Interface...
Setting Alternate Setting #0 ...
the selected serial port Setting Alternate Setting #0 ...
 does not exist or your board is not connected
Determining device status: state = dfuIDLE, status = 0
dfuIDLE, continuing
DFU mode device DFU version 011a
Device returned transfer size 2048
main upload failed
dfu-util: Error: File ID 040e:0091 does not match device (040e:df11 or 0483:df11)
```

**Comment by terrillmoore** [comment] 2021-10-15 19:39
@mhmayyan sorry you're having troubles.

Your device is dropping out of DFU mode after the first download. That's odd; it could be due to a number of different issues. We'll try to reproduce here.

But the good news is that the first step (bootloader download) is working. You really only have to do that once. If you choose "DFU without bootloader" in the UI, it will only download the app, which should work. That is:

![image](https://user-images.githubusercontent.com/19333103/137544449-46590fee-39fb-495c-b04e-80ff292d1b04.png)

**Comment by terrillmoore** [comment] 2021-10-18 12:29
Sorry you're having problems; we'll try to duplicate here.

**Comment by terrillmoore** [comment] 2021-10-19 15:30
This got auto-closed by the pull request which was just merged. You should be able to patch your release by downloading the file (https://raw.githubusercontent.com/mcci-catena/Arduino_Core_STM32/main/tools/linux/stm32l0-upload), and putting into tools/linux in your BSP copy. Or you may have to wait for a little while, as we'll have to prepare a release.

**Comment by terrillmoore** [comment] 2021-10-19 19:42
@mhmayyan please update your BSP to v3.0.4 and try. We believe this is now fixed. (Very small chance of an error in json file for the BSP as I don't have a proper test setup.)

**Comment by mhmayyan** [comment] 2021-10-19 21:37
I tested the new BSP (V3.0.4). It works now on Linux (Ubuntu) and Windows 10. Thank you.

**Closed as completed** 2021-10-20 00:42 UTC
Labels: bug
